import tkinter as tk

#Erick Alejandro Ramírez González A01637436
#Juan Antonio Hernández Ruiz A01638014
#Gael Nicolas Duncan Castillo A01637417

#used with https://world.openfoodfacts.org/

root = tk.Tk()

root.title("The Healthiest App")

canvas = tk.Canvas(root, height = 580, width = 780)
canvas.pack()

background_image = tk.PhotoImage(file = 'food.png')
background_label = tk.Label(root, image = background_image)
background_label.place (relwidth=1, relheight=1)

label = tk.Label(root, text = 'Welcome to The healthiest', bg = '#10c461', fg = "white", font=40)
label.place(relx = 0.35, rely = 0)

frame = tk.Frame(root, bg = '#10c461', bd = 5)
frame.place(relx = 0.5, rely = 0.1, relwidth = 0.75, relheight = 0.1, anchor = 'n')

entry = tk.Entry(frame, font = 40)
entry.place(relwidth = 0.65, relheight = 1)

button = tk.Button(frame, text = "Get the info", font = 10, command = lambda: Get_Info(entry.get()))
button.place(relx = 0.69, relwidth = 0.305, relheight = 1)

lower_frame = tk.Frame (root, bg = '#10c461', bd = 10)
lower_frame.place(relx = 0.5, rely=0.25, relwidth=0.75, relheight=0.6, anchor = 'n')

label = tk.Label(lower_frame)
label.place(relwidth=1, relheight = 1)

def Get_Info(entry):
    if entry == "Nutella":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "sugar, palm oil, hazelnuts 13%, cocoa lean to 7.4%, vanillin") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "skimmed milk powder 6,6%, whey powder, emulsifiers : lecithins [soy]") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "30.9 g Fat in high quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "10.6 g Saturated fat in high quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "56.3 g Sugars in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "0.107 g Salt in low quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 30.9g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 57.5g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 6.3g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.107g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 539kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Eggs":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Eggs") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "9.8 g Fat in moderate quantity" ) 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "2.6 g Saturated fat in moderate quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.3 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "0.3 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Energy = 140 kcal") 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 9.8 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 0.3 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 12.7 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.3g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "   ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Meat":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Cow meat") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "14 g Fat in moderate quantity" ) 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "6.5 g Saturated fat in high quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.5 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "1.5 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Energy = 207 kcal") 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 14 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 0.9 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 19.4 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.5g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "   ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Ham":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Ham (90%), salt, antioxidants, spices, fragances") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "2.5 g Fat in low quantity" ) 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0.9 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.9 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "1.9 g Salt in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Energy = 431 kcal") 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 2.5 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 0.9 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 19 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.9 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "   ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Beans":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "beans (51%), tomatoes (34%), water, sugar, spirit vinegar,") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "modified cornflour, salt, spice extracts, herb extract") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0.2 g Fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.1 g Saturated fat in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "5 g Sugars in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "0.6 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0.2 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 12.9 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 4.7 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.6 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 79 kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Lays":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "potatoes 65%, vegetable oils (sunflower, rapeseed in variable proportions), salt,") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "34 g Fat in high quantity" ) 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "4.2 g Saturated fat in moderate quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.5 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "1.1 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Energy = 551 kcal") 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 34 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 53 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 6.3 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.1 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "   ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Spaghetti":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "pasta of durum wheat semolina, water, gluten") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "2 g Fat in low quantity" ) 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0.5 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "3.5 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "0.013 g Salt in low quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Energy = 359 kcal") 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 2 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 70.9 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 12.8 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.013 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "   ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Oreo":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "wheat flour, sugar, vegetable oils (palm, palm kernel), lean cocoa powder 4,6 %,") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = " wheat starch, glucose-fructose syrup, baking powder, salt, emulsifiers") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "19 g Fat in moderate quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "5.2 g Saturated fat in high quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "38 g Sugars in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "0.74 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 19 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 68g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 5.4g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.74g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 474kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Redbull":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Water, sucrose, glucose, citric citric acid, carbonic acid, taurine") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "acidity regulator, caffeine, vitamins, flavoring, coloring") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100 ml:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Saturated fat in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "11 g Sugars in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "0.1 g Salt in low quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100ml:", fg='red') 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 11g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 0g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.1g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 46kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Integral bread":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Corn syrup, wheat gluten, yeast, glucose, vegetable oil, milk, eggs") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "sesame, nut, iodized salt, monocalcium phosphate, calcium propinate") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "30.38g Fat in high quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "1.01g Saturated fat in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "6.76g Sugars in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "0.971 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 3.38g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 47.3g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 10.1g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0.971g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 260kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Mineral water":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Carbonated mineral water") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100 ml:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Fat in low quantity") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "3.18e-05 g Salt in low quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100 ml:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text ='Energy = 0 kcal') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 0 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 0 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "    ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Chicken nuggets":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "specialties breaded chicken, celery , gluten, wheat") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100 g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "13 g Fat in moderate quantity") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "1.6 g Saturated fat in moderate quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.4 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "1.2 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100 g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text ='Energy = 251 kcal') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 13 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 17 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 16 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.2 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "    ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Mustard":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "water, mustard seeds, malt vinegar (barley), sugar, salt, honey, spices, natural aroma,") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "thickening (xanthan gum), paprika extract, gluten") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "5 g Fat in moderate quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.3 g Saturated fat in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "5.3 g Sugars in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "2.4 g Salt in high quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 5 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 9.3 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 5.4 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 2.4 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 118 kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Soy sauce":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "water, soybeans , wheat , salt, gluten") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Fat in low quantity") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.6 g Sugars in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "16.9 g Salt in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text ='Energy = 325 kcal') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 3.2 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 10 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 16.9 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "    ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Ketchup":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "corn, sugar, aroma of malt of barley , salt, vitamins and minerals") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "0.1 g Fat in low quantity") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0.1 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "22.8 g Sugars in high quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "1.8 g Salt in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text ='Energy = 102 kcal') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0.1 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 23.2 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 1.2 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.8 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "    ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Pickles":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "gherkins, water, spirit vinegar, glucose-fructose syrup, salt,") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "dill, onion, red pepper, mustard seeds , flavour, sugar") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0.2 g Fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "0.1 g Saturated fat in low quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "4.7 g Sugars in low quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "1.6 g Salt in high quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0.2 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 4.9 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 0.9 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.6 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 30 kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Cheddar cheese":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "cheeses (of which cheddar 25%),  water, butter, protein and lactose in milk,") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = " skim milk powder, salts of cast iron") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "21 g Fat in high quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "14 g Saturated fat in high quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "4 g Sugars in low quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "3.2 g Salt in high quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 21g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 4g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 15g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 3.2g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Energy = 265kcal") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)
        
    elif entry == "Coke":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "Carbonated water, sugar, colour (caramel e150d), phosphoric acid, flavouring including caffeine") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100 ml:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Fat in low quantity") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "10.6 g Sugars in high quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "0 g Salt in low quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100 ml:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text ='Energy = 42 kcal') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 10.6 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 0 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 0 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "    ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Corn flakes":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = "corn, sugar, aroma of malt of barley , salt, vitamins and minerals") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg='red') 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "0.9 g Fat in low quantity") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "0.2 g Saturated fat in low quantity") 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "8 g Sugars in moderate quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "1.13 g Salt in moderate quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text ='Energy = 378 kcal') 
        label.place(relwidth=1, rely=0.405)
        label = tk.Label(lower_frame, text = "Fat = 0.9 g") 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Carbohydrates = 84 g") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Proteins = 7 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Salt = 1.13 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "    ") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "  ") 
        label.place(relwidth=1, rely=0.710)

    elif entry == "Bacon":
        label = tk.Label(lower_frame, text = "Ingredients:", fg='red') 
        label.place( rely=0.00000000000000000000001, relwidth=1)
        label = tk.Label(lower_frame, text = " chopped steak pure beef breed charolais cooked origin france 27,7%, mayonnaise, onions, pre-fried") 
        label.place( rely=0.05, relwidth=1)
        label = tk.Label(lower_frame, text = "egg yolk, vinegar, sugar, salt, concentrated lemon juice], emmental 8.3 per cent, cooked bacon smoked") 
        label.place( rely=0.1, relwidth=1)
        label = tk.Label(lower_frame, text = "green pepper 0,4%, sherry vinegar, veal stock, black pepper") 
        label.place( rely=0.15, relwidth=1)
        label = tk.Label(lower_frame, text = "Nutrient levels for 100g:", fg= 'red') 
        label.place( rely=0.205, relwidth=1)
        label = tk.Label(lower_frame, text = "19 g Fat in moderate quantity") 
        label.place(rely=0.255, relwidth=1)
        label = tk.Label(lower_frame, text = "5.1 g Saturated fat in high quantity") 
        label.place(relwidth=1, rely=0.305)
        label = tk.Label(lower_frame, text = "1.8 g Sugars in low quantity") 
        label.place(relwidth=1, rely=0.355)
        label = tk.Label(lower_frame, text = "1.1 g Salt in moderate quantity") 
        label.place(relx=0.35, rely=0.405)
        label = tk.Label(lower_frame, text = "Nutrition facts for 100g:", fg='red') 
        label.place(relwidth=1, rely=0.460)
        label = tk.Label(lower_frame, text = "Energy = 319 kcal") 
        label.place(relwidth=1, rely=0.510)
        label = tk.Label(lower_frame, text = "Fat = 19 g") 
        label.place(relwidth=1, rely=0.560)
        label = tk.Label(lower_frame, text = "Carbohydrates = 24 g") 
        label.place(relwidth=1, rely=0.610)
        label = tk.Label(lower_frame, text = "Proteins = 12 g") 
        label.place(relwidth=1, rely=0.660)
        label = tk.Label(lower_frame, text = "Salt = 1.1 g") 
        label.place(relwidth=1, rely=0.710)

    else:
        label = tk.Label(lower_frame, text = "Couldn't find it", fg='red', font= 10000) 
        label.place(relx=0.0000000000000000000001, rely=0.000000000000000000001, relwidth=1, relheight=1)

root.mainloop()